### ISSUE TITLE
rdbnomics doesn't work

### ISSUE THREAD

**Issue by msh855** [dbnomics/rdbnomics#1]
Sadly, I try to use your r client but does not work

All messages were of the type 

Error in ... 
could not find function ... 

for example, 

```
df1    <- rdb_by_codes('AMECO','ZUTN','EA19.1.0.0.0.ZUTN')
Error in rdb_by_codes("AMECO", "ZUTN", "EA19.1.0.0.0.ZUTN") : 
  could not find function "rdb_by_codes"

```

**Comment by thomasbrand** [comment]
It's strange, I don't have this problem. Did you run ```library(rdbnomics)``` after installing the package?

**Comment by msh855** [comment]
@thomasbrand It was my mistake. I use the pacman package to install together many libraries, and misspecified the installation for rdbinomics. Sorry, I should have being more careful. Amateur level mistake !
