### ISSUE TITLE
What is dbnomics() function?

### ISSUE THREAD

**Issue by blu2ego** [dbnomics/rdbnomics#2]
Thank you for awesome package! But, I have a problem. 
I found out through r-bloggers.com(https://www.r-bloggers.com/access-the-free-economic-database-dbnomics-with-r-2/), and tried to run the example code. But, dbnomics() function in the example code for visualization using ggplot2 doesn't run, so I tried to find what is dbnomics() function , but I can't find that function. 
I want to know whether dbnomics() function is supported from you or not.
Thank you so much.

**Comment by thomasbrand** [comment]
Thanks! On this page https://macro.cepremap.fr/article/2019-10/rdbnomics-tutorial/, you have a link to the sources, here : https://git.nomics.world/macro/macro.nomics.world/blob/master/content/rdbnomics-tutorial/rdbnomics-tutorial.Rmd. Line 79, the function dbnomics() is defined.

**Comment by s915** [comment]
Thanks @blu2ego !
The function `dbnomics()` is not included in the package because it is just a ggplot2 theme used to have better graphics.
You can also find its definition in the vignette *"9 Appendix"* => *"9.1 ggplot2 function dbnomics() used in the vignette"* with :
```r
library(rdbnomics)
vignette("rdbnomics")
```

**Comment by blu2ego** [comment]
Thanks @thomasbrand  and @s915 !
I was able to solve the problem that code in blog returned error with your help.

P.S. @thomasbrand , Sorry for delayed reply. I was away from internet for some time.
